(function(){
  const STYLE=`#tradePlan{margin-top:16px}.tp-grid{display:grid;grid-template-columns:1.2fr 1fr 1fr 1fr;gap:12px;margin-top:12px}.tp-card{background:#151821;border:1px solid #252b37;border-radius:12px;padding:14px}.tp-card small{display:block;color:#8e98aa;font-size:11px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:6px}.tp-card b{font-size:18px}.tp-wide{grid-column:span 2}.tp-signal{font-size:24px;font-weight:800}.tp-buy{color:#65dc91}.tp-sell{color:#ff7676}.tp-wait{color:#f5b942}.tp-note{color:#b1b9c8;line-height:1.55}.tp-list{display:flex;gap:8px;flex-wrap:wrap}.tp-tag{padding:6px 9px;border-radius:999px;background:#10131a;border:1px solid #2a3140;color:#cdd4df;font-size:12px}.tp-pips{font-size:12px!important;color:#d9dee7;margin-top:4px}.tp-pips span{color:#8e98aa;font-weight:500}.gx-chart-card{margin-top:16px}.gx-chart-wrap{height:460px;position:relative;background:#0c0f14;border:1px solid #252b37;border-radius:12px;overflow:hidden}.gx-chart{width:100%;height:100%;display:block}.gx-chart-legend{position:absolute;top:10px;left:12px;display:flex;gap:8px;flex-wrap:wrap;pointer-events:none}.gx-chip{padding:6px 9px;border-radius:8px;background:#12161f;border:1px solid #2a3140;color:#cbd2de;font-size:11px}.gx-chip strong{margin-right:4px}.gx-chart-note{margin-top:10px;color:#8e98aa;font-size:12px;line-height:1.5}@media(max-width:900px){.tp-grid{grid-template-columns:1fr 1fr}.tp-wide{grid-column:span 2}.gx-chart-wrap{height:400px}}@media(max-width:600px){.tp-grid{grid-template-columns:1fr}.tp-wide{grid-column:span 1}.gx-chart-wrap{height:340px}}`;
  function addStyle(){if(document.getElementById('tp-style'))return;const s=document.createElement('style');s.id='tp-style';s.textContent=STYLE;document.head.appendChild(s)}
  function ensurePanel(){if(document.getElementById('tradePlan'))return;const host=document.getElementById('analysis');if(!host)return;const wrap=document.createElement('div');wrap.id='tradePlan';wrap.className='card';wrap.innerHTML='<div class="card-top"><span>TRADE PLAN • WAIT / ENTRY MAP</span><span id="tpMode" class="mini-pill">LIVE DATA</span></div><div class="tp-grid"><div class="tp-card tp-wide"><small>FINAL SIGNAL</small><div id="tpSignal" class="tp-signal tp-wait">WAIT / NO TRADE</div><div id="tpReason" class="tp-note">Run the AI analysis to populate the plan.</div></div><div class="tp-card"><small>CONFIDENCE</small><b id="tpConfidence">—</b></div><div class="tp-card"><small>R:R</small><b id="tpRR">—</b></div><div class="tp-card"><small>BUY ABOVE</small><b id="tpBuy">—</b></div><div class="tp-card"><small>SELL BELOW</small><b id="tpSell">—</b></div><div class="tp-card"><small>ENTRY ZONE</small><b id="tpEntry">—</b></div><div class="tp-card"><small>STOP LOSS</small><b id="tpSL">—</b><div id="tpSLPips" class="tp-pips"><span>Pips:</span> —</div></div><div class="tp-card"><small>TP1</small><b id="tpTP1">—</b><div id="tpTP1Pips" class="tp-pips"><span>Distance:</span> —</div></div><div class="tp-card"><small>TP2</small><b id="tpTP2">—</b><div id="tpTP2Pips" class="tp-pips"><span>Distance:</span> —</div></div><div class="tp-card"><small>PIP SCALE</small><b>1 pip = 0.01</b><div class="tp-pips"><span>Gold convention</span></div></div><div class="tp-card tp-wide"><small>WAIT FOR / TRIGGER</small><div id="tpWait" class="tp-list"><span class="tp-tag">Liquidity sweep</span><span class="tp-tag">Structure break</span><span class="tp-tag">Retest</span></div></div></div>';host.appendChild(wrap)}
  function ensureChart(){if(document.getElementById('gxChartCard'))return;const host=document.getElementById('analysis');if(!host)return;const card=document.createElement('div');card.id='gxChartCard';card.className='card gx-chart-card';card.innerHTML='<div class="card-top"><span>AI SIGNAL CHART • XAU/USD</span><span id="gxChartStatus" class="mini-pill">WAITING</span></div><div class="gx-chart-wrap"><canvas id="gxChart" class="gx-chart"></canvas><div id="gxLegend" class="gx-chart-legend"></div></div><div id="gxChartNote" class="gx-chart-note">Run AI analysis to draw the live candle map, BUY/SELL trigger levels, Entry, SL, TP and detected FVG zones.</div>';host.appendChild(card)}
  const n=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:null};
  const f=v=>{const x=n(v);return x===null?'—':x.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})};
  const pips=v=>{const x=n(v);return x===null?'—':Math.round(Math.abs(x)*100).toLocaleString('en-US')+' pips'};
  function set(id,val){const e=document.getElementById(id);if(e)e.textContent=val}
  function updatePlan(out){ensurePanel();ensureChart();window.__lastGoldXOut=out;const a=out?.analysis||{},c=out?.context||{},bias=String(a.bias||'NO TRADE').toUpperCase();const sig=bias.includes('BUY')?'BUY':bias.includes('SELL')?'SELL':'WAIT / NO TRADE';const cls=sig==='BUY'?'tp-buy':sig==='SELL'?'tp-sell':'tp-wait';const se=document.getElementById('tpSignal');if(se){se.textContent=sig;se.className='tp-signal '+cls}
    const entry=n(a.entry),sl=n(a.stopLoss),tp1=n(a.tp1),tp2=n(a.tp2);
    set('tpConfidence',n(a.confidence)!==null?n(a.confidence)+'%':'—');set('tpRR',a.riskReward||'—');
    set('tpBuy',n(c.recentRangeHigh)!==null?f(c.recentRangeHigh):'—');set('tpSell',n(c.recentRangeLow)!==null?f(c.recentRangeLow):'—');
    set('tpEntry',entry!==null?f(entry):'Wait for confirmation');set('tpSL',sl!==null?f(sl):'—');set('tpTP1',tp1!==null?f(tp1):'—');set('tpTP2',tp2!==null?f(tp2):'—');
    set('tpSLPips',sl!==null&&entry!==null?`Pips: ${pips(entry-sl)}`:'Pips: —');set('tpTP1Pips',tp1!==null&&entry!==null?`Distance: ${pips(tp1-entry)}`:'Distance: —');set('tpTP2Pips',tp2!==null&&entry!==null?`Distance: ${pips(tp2-entry)}`:'Distance: —');
    set('tpReason',a.reasoning||'—');set('tpMode',out?.mode==='live-ohlc-plus-ai'?'TWELVE DATA + GEMINI':'LIVE OHLC');
    const wait=document.getElementById('tpWait');if(wait){const tags=[];if(sig==='WAIT / NO TRADE'){tags.push('Sweep outer liquidity','BOS/CHOCH','Retest / displacement','Avoid mid-range')}else{tags.push('Retest of entry','Confirm momentum','Respect invalidation')}wait.innerHTML=tags.map(x=>'<span class="tp-tag">'+x+'</span>').join('')}
    drawChart(out);
  }
  async function drawChart(out){ensureChart();const status=document.getElementById('gxChartStatus');try{let candles=Array.isArray(out?.candles)?out.candles:null;if(!candles){const tf=document.querySelector('.tf.active')?.dataset.tf||'15min';const r=await fetch('/api/candles?interval='+encodeURIComponent(tf));const d=await r.json();if(!r.ok)throw Error(d.error||'Candle feed unavailable');candles=d.candles}if(!candles?.length)throw Error('No candles returned');const data=candles.slice(-80);const canvas=document.getElementById('gxChart');if(!canvas)return;const rect=canvas.getBoundingClientRect();const dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(rect.width*dpr));canvas.height=Math.max(1,Math.floor(rect.height*dpr));const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);const W=rect.width,H=rect.height;ctx.clearRect(0,0,W,H);const hi=Math.max(...data.map(x=>Number(x.high)));const lo=Math.min(...data.map(x=>Number(x.low)));const pad=(hi-lo)*0.08||1;const max=hi+pad,min=lo-pad;const y=p=>H-26-((p-min)/(max-min))*(H-46);const left=46,right=90,plotW=Math.max(10,W-left-right),step=plotW/data.length,bodyW=Math.max(3,step*0.58);ctx.font='11px Inter,Arial';ctx.textBaseline='middle';ctx.strokeStyle='rgba(255,255,255,.06)';ctx.lineWidth=1;for(let i=0;i<=5;i++){const gy=24+i*((H-50)/5);ctx.beginPath();ctx.moveTo(left,gy);ctx.lineTo(W-right,gy);ctx.stroke();const p=max-(i/5)*(max-min);ctx.fillStyle='#7d8797';ctx.fillText(f(p),4,gy)}data.forEach((c,i)=>{const x=left+i*step+step/2,o=n(c.open),cl=n(c.close),h=n(c.high),l=n(c.low);if([o,cl,h,l].some(v=>v===null))return;const up=cl>=o;ctx.strokeStyle=up?'#65dc91':'#ff7676';ctx.fillStyle=up?'#65dc91':'#ff7676';ctx.beginPath();ctx.moveTo(x,y(h));ctx.lineTo(x,y(l));ctx.stroke();const top=y(Math.max(o,cl)),bot=y(Math.min(o,cl));ctx.fillRect(x-bodyW/2,top,bodyW,Math.max(1,bot-top))});
      function line(price,label,dashed){if(n(price)===null)return;const yy=y(price);ctx.save();ctx.strokeStyle=label.includes('BUY')?'#65dc91':label.includes('SELL')?'#ff7676':label==='SL'?'#ff7676':label.startsWith('TP')?'#82c7ff':'#f5b942';ctx.lineWidth=1.5;if(dashed)ctx.setLineDash([6,4]);ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(W-right,yy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=ctx.strokeStyle;ctx.fillRect(W-right+4,yy-9,100,18);ctx.fillStyle='#0b0e13';ctx.fillText(label+' '+f(price),W-right+8,yy);ctx.restore()}
      const cxt=out?.context||{};line(cxt.recentRangeHigh,'BUY ABOVE',true);line(cxt.recentRangeLow,'SELL BELOW',true);line(out?.analysis?.entry,'ENTRY',false);line(out?.analysis?.stopLoss,'SL',false);line(out?.analysis?.tp1,'TP1',false);line(out?.analysis?.tp2,'TP2',false);
      const fvgs=Array.isArray(cxt.recentFVGs)?cxt.recentFVGs.slice(-4):[];fvgs.forEach(zone=>{const a=n(zone.low),b=n(zone.high);if(a===null||b===null)return;const yy1=y(Math.max(a,b)),yy2=y(Math.min(a,b));ctx.fillStyle=zone.type==='bullish FVG'?'rgba(101,220,145,.10)':'rgba(255,118,118,.10)';ctx.fillRect(left,yy1,W-right-left,Math.max(4,yy2-yy1));ctx.strokeStyle=zone.type==='bullish FVG'?'rgba(101,220,145,.45)':'rgba(255,118,118,.45)';ctx.strokeRect(left,yy1,W-right-left,Math.max(4,yy2-yy1))});
      const leg=document.getElementById('gxLegend');if(leg)leg.innerHTML='<span class="gx-chip"><strong>BUY ABOVE</strong>'+f(cxt.recentRangeHigh)+'</span><span class="gx-chip"><strong>SELL BELOW</strong>'+f(cxt.recentRangeLow)+'</span>'+(n(out?.analysis?.entry)!==null?'<span class="gx-chip"><strong>ENTRY</strong>'+f(out.analysis.entry)+'</span>':'<span class="gx-chip"><strong>WAIT</strong>Confirmation</span>');set('gxChartStatus',`LIVE • ${data.length} candles`);const note=document.getElementById('gxChartNote');if(note){const b=String(out?.analysis?.bias||'NO TRADE').toUpperCase();note.textContent=b.includes('BUY')?`BUY setup detected. Entry/SL/TP lines are drawn from the AI plan.`:b.includes('SELL')?`SELL setup detected. Entry/SL/TP lines are drawn from the AI plan.`:`No confirmed trade setup. BUY ABOVE and SELL BELOW are trigger levels, not immediate entries.`}}
    catch(e){set('gxChartStatus','ERROR');const note=document.getElementById('gxChartNote');if(note)note.textContent=e.message||'Chart unavailable'}}
  function wrapFetch(){if(window.__goldxFetchWrapped)return;window.__goldxFetchWrapped=true;const orig=window.fetch.bind(window);window.fetch=function(input,init){return orig(input,init).then(r=>{try{const u=typeof input==='string'?input:input?.url||'';if(u.includes('/api/ai')){const clone=r.clone();clone.json().then(updatePlan).catch(()=>{})}}catch{}return r})}}
  function boot(){addStyle();ensurePanel();ensureChart();wrapFetch();window.addEventListener('resize',()=>{if(window.__lastGoldXOut)drawChart(window.__lastGoldXOut)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
