(function(){
  const STYLE=`#tradePlan{margin-top:16px}.tp-grid{display:grid;grid-template-columns:1.2fr 1fr 1fr 1fr;gap:12px;margin-top:12px}.tp-card{background:#151821;border:1px solid #252b37;border-radius:12px;padding:14px}.tp-card small{display:block;color:#8e98aa;font-size:11px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:6px}.tp-card b{font-size:18px}.tp-wide{grid-column:span 2}.tp-signal{font-size:24px;font-weight:800}.tp-buy{color:#65dc91}.tp-sell{color:#ff7676}.tp-wait{color:#f5b942}.tp-lines{display:flex;gap:10px;flex-wrap:wrap}.tp-line{padding:8px 10px;border-radius:9px;background:#10131a;border:1px solid #262d3a}.tp-line span{color:#8e98aa;margin-right:6px}.tp-note{color:#b1b9c8;line-height:1.55}.tp-list{display:flex;gap:8px;flex-wrap:wrap}.tp-tag{padding:6px 9px;border-radius:999px;background:#10131a;border:1px solid #2a3140;color:#cdd4df;font-size:12px}@media(max-width:900px){.tp-grid{grid-template-columns:1fr 1fr}.tp-wide{grid-column:span 2}}@media(max-width:600px){.tp-grid{grid-template-columns:1fr}.tp-wide{grid-column:span 1}}`;
  function addStyle(){if(document.getElementById('tp-style'))return;const s=document.createElement('style');s.id='tp-style';s.textContent=STYLE;document.head.appendChild(s)}
  function ensurePanel(){if(document.getElementById('tradePlan'))return;const host=document.getElementById('analysis');if(!host)return;const wrap=document.createElement('div');wrap.id='tradePlan';wrap.className='card';wrap.innerHTML='<div class="card-top"><span>TRADE PLAN • WAIT / ENTRY MAP</span><span id="tpMode" class="mini-pill">LIVE DATA</span></div><div class="tp-grid"><div class="tp-card tp-wide"><small>FINAL SIGNAL</small><div id="tpSignal" class="tp-signal tp-wait">WAIT / NO TRADE</div><div id="tpReason" class="tp-note">Run the AI analysis to populate the plan.</div></div><div class="tp-card"><small>CONFIDENCE</small><b id="tpConfidence">—</b></div><div class="tp-card"><small>R:R</small><b id="tpRR">—</b></div><div class="tp-card"><small>BUY ABOVE</small><b id="tpBuy">—</b></div><div class="tp-card"><small>SELL BELOW</small><b id="tpSell">—</b></div><div class="tp-card"><small>ENTRY ZONE</small><b id="tpEntry">—</b></div><div class="tp-card"><small>STOP LOSS</small><b id="tpSL">—</b></div><div class="tp-card"><small>TP1</small><b id="tpTP1">—</b></div><div class="tp-card"><small>TP2</small><b id="tpTP2">—</b></div><div class="tp-card tp-wide"><small>WAIT FOR / TRIGGER</small><div id="tpWait" class="tp-list"><span class="tp-tag">Liquidity sweep</span><span class="tp-tag">Structure break</span><span class="tp-tag">Retest</span></div></div></div>';
host.appendChild(wrap)}
  const n=v=>{const x=Number(String(v??'').replace(/,/g,''));return Number.isFinite(x)?x:null};
  const f=v=>{const x=n(v);return x===null?'—':x.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})};
  function set(id,val){const e=document.getElementById(id);if(e)e.textContent=val}
  function update(out){ensurePanel();const a=out?.analysis||{},c=out?.context||{},bias=String(a.bias||'NO TRADE').toUpperCase();const sig=bias.includes('BUY')?'BUY':bias.includes('SELL')?'SELL':'WAIT / NO TRADE';const cls=sig==='BUY'?'tp-buy':sig==='SELL'?'tp-sell':'tp-wait';const se=document.getElementById('tpSignal');if(se){se.textContent=sig;se.className='tp-signal '+cls}
    set('tpConfidence',n(a.confidence)!==null?n(a.confidence)+'%':'—');set('tpRR',a.riskReward||'—');
    set('tpBuy',n(c.recentRangeHigh)!==null?f(c.recentRangeHigh):'—');set('tpSell',n(c.recentRangeLow)!==null?f(c.recentRangeLow):'—');
    set('tpEntry',n(a.entry)!==null?f(a.entry):'Wait for confirmation');set('tpSL',n(a.stopLoss)!==null?f(a.stopLoss):'—');set('tpTP1',n(a.tp1)!==null?f(a.tp1):'—');set('tpTP2',n(a.tp2)!==null?f(a.tp2):'—');
    set('tpReason',a.reasoning||'—');set('tpMode',out?.mode==='live-ohlc-plus-ai'?'TWELVE DATA + GEMINI':'LIVE OHLC');
    const wait=document.getElementById('tpWait');if(wait){const tags=[];if(sig==='WAIT / NO TRADE'){tags.push('Sweep outer liquidity','15m BOS/CHOCH','Retest / displacement','Avoid mid-range entries')}else{tags.push('Retest of entry','Confirm momentum','Respect invalidation')}wait.innerHTML=tags.map(x=>'<span class="tp-tag">'+x+'</span>').join('')}
  }
  function wrapFetch(){if(window.__goldxFetchWrapped)return;window.__goldxFetchWrapped=true;const orig=window.fetch.bind(window);window.fetch=function(input,init){return orig(input,init).then(async r=>{try{const u=typeof input==='string'?input:input?.url||'';if(u.includes('/api/ai')){const clone=r.clone();clone.json().then(update).catch(()=>{})}}catch{}return r})}}
  function boot(){addStyle();ensurePanel();wrapFetch()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
